pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'sridinesh/mavenproject'
    }

    stages {
        stage('Build with Maven') {
            steps {
                dir('Sports-Shop-Landing-Page-main') {
                    script {
                        docker.image('maven:latest').inside('-u root') {
                            sh 'mvn -T 4 -Dmaven.repo.local=target/.m2repo clean install'
                        }
                    }
                }
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                dir('Sports-Shop-Landing-Page-main') {
                    sh 'chmod +x deploy.sh'
                    sh './deploy.sh'
                }
            }
        }
    }
}
